{{- if and .Values.api.enabled}}
{{- $usePvc := not (or .Values.externalS3.enabled .Values.externalOSS.enabled .Values.externalAzureBlobStorage.enabled .Values.externalGCS.enabled .Values.externalCOS.enabled) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
{{ include "dify.ud.annotations" . | indent 4 }}
    descriptions: api
  labels:
{{- include "dify.labels" . | nindent 4 }}
    component: api
    # app: {{ template "dify.api.fullname" . }}
{{ include "dify.ud.labels" . | indent 4 }}
  name: {{ template "dify.api.fullname" . }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
{{- include "dify.selectorLabels" . | nindent 6 }}
      component: api
      {{/*
      # Required labels for istio
      # app: {{ template "dify.api.fullname" . }}
      # version: {{ (print "v" .Values.serviceMesh.version) | quote }}
      */}}
  template:
    metadata:
      annotations:
        checksum/api-config: {{ include (print $.Template.BasePath "/api-config.yaml") . | sha256sum }}
        checksum/api-secret: {{ include (print $.Template.BasePath "/api-secret.yaml") . | sha256sum }}
{{ include "dify.ud.annotations" . | indent 8 }}
      labels:
{{- include "dify.selectorLabels" . | nindent 8 }}
        component: api
        {{/*
        # Required labels for istio
        # app: {{ template "dify.api.fullname" . }}
        # version: {{ (print "v" .Values.serviceMesh.version) | quote }}
        */}}
{{ include "dify.ud.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ include "dify.api.serviceAccountName" . }}
      {{- if eq .Release.Name "dify"}}
      {{/*
      Disable service environment variables,
      otherwise they will clash with `DIFY_PORT` which is needed in entrypoint.sh
      */}}
      enableServiceLinks: false
      {{- end }}
      {{- if .Values.image.api.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.api.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- if .Values.api.podSecurityContext }}
      securityContext:
{{ toYaml .Values.api.podSecurityContext | indent 8 }}
      {{- end }}
      initContainers:
      - name: update-ca-certificates
        image: "{{ .Values.image.api.repository }}:{{ default .Chart.AppVersion .Values.image.api.tag }}"
        command:
        - /bin/sh
        - -c
        - |
          # 1. 更新系统根证书
          # 将自定义证书复制到 CA 目录并更新
          ls -l /custom-certs/
          cp /custom-certs/* /usr/local/share/ca-certificates/
          update-ca-certificates

          # 将生成的系统证书复制到共享 Volume
          cp -r /etc/ssl/certs/* /shared-ssl/

          # 2. 生成 Python 证书包
          # 获取 Python 默认证书路径
          CACERT_PATH=$(python -c "import certifi; print(certifi.where())")
          # 合并默认证书和自定义证书
          cat $CACERT_PATH /custom-certs/* > /python-ca/ca-bundle.pem
        securityContext:
          privileged: true
        volumeMounts:
        - name: custom-ca-cert
          mountPath: /custom-certs
        - name: shared-ssl-certs   # 挂载系统证书 Volume
          mountPath: /shared-ssl
        - name: python-ca-bundle   # 挂载 Python 证书 Volume
          mountPath: /python-ca
      containers:
      - image: "{{ .Values.image.api.repository }}:{{ default .Chart.AppVersion .Values.image.api.tag }}"
        imagePullPolicy: "{{ .Values.image.api.pullPolicy }}"
        name: api
        {{- if .Values.api.customLivenessProbe }}
        livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.api.customLivenessProbe "context" $) | nindent 10 }}
        {{- else if .Values.api.livenessProbe.enabled }}
        livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.api.livenessProbe "enabled") "context" $) | nindent 10 }}
          httpGet:
            path: /health
            port: api
        {{- end }}
        {{- if .Values.api.customReadinessProbe }}
        readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.api.customReadinessProbe "context" $) | nindent 10 }}
        {{- else if .Values.api.readinessProbe.enabled }}
        readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.api.readinessProbe "enabled") "context" $) | nindent 10 }}
          httpGet:
            path: /health
            port: api
        {{- end }}
        {{- if .Values.api.customStartupProbe }}
        startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.api.customStartupProbe "context" $) | nindent 10 }}
        {{- else if .Values.api.startupProbe.enabled }}
        startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.api.startupProbe "enabled") "context" $) | nindent 10 }}
          tcpSocket:
            port: api
        {{- end }}
        {{- if .Values.api.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.api.containerSecurityContext | indent 10 }}
        {{- end }}
        env:
        - name: SSL_CERT_FILE         # 指定 Python 使用自定义证书包
          value: /etc/python-certs/ca-bundle.pem
        {{- if .Values.sandbox.enabled }}
        - name: CODE_EXECUTION_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "dify.sandbox.fullname" . }}
              key: "API_KEY"
        {{- end }}
        {{- if .Values.api.extraEnv }}
          {{- toYaml .Values.api.extraEnv | nindent 8 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ template "dify.api.fullname" . }}
        - secretRef:
            name: {{ template "dify.api.fullname" . }}
        ports:
          - name: api
            containerPort: 5001
            protocol: TCP
        resources:
          {{- toYaml .Values.api.resources | nindent 12 }}
        volumeMounts:
        {{- if $usePvc }}
        - name: app-data
          mountPath: {{ .Values.api.persistence.mountPath | quote }}
          subPath: {{ .Values.api.persistence.persistentVolumeClaim.subPath | default "" }}
        {{- end }}
        - name: shared-ssl-certs      # 挂载系统证书
          mountPath: /etc/ssl/certs   # 覆盖系统证书目录
        - name: python-ca-bundle      # 挂载 Python 证书包
          mountPath: /etc/python-certs/ca-bundle.pem
          subPath: ca-bundle.pem
    {{- if and (.Values.nodeSelector) (not .Values.api.nodeSelector) }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.api.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.api.nodeSelector | indent 8 }}
    {{- end }}
    {{- if and (.Values.affinity) (not .Values.api.affinity) }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.api.affinity }}
      affinity:
{{ toYaml .Values.api.affinity | indent 8 }}
    {{- end }}
    {{- if and (.Values.tolerations) (not .Values.api.tolerations) }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.api.tolerations }}
      tolerations:
{{ toYaml .Values.api.tolerations | indent 8 }}
    {{- end }}
      volumes:
      {{- if $usePvc }}
      - name: app-data
        persistentVolumeClaim:
          claimName: {{ .Values.api.persistence.persistentVolumeClaim.existingClaim | default (printf "%s" (include "dify.fullname" . | trunc 58)) }}
      {{- end }}
      - name: custom-ca-cert
        configMap:
          name: dify-custom-ca-cert
      - name: shared-ssl-certs   # 系统根证书目录
        emptyDir: {}
      - name: python-ca-bundle   # Python 自定义证书包
        emptyDir: {}
{{- end }}