apiVersion: v1
kind: ConfigMap
metadata:
  name: dify-custom-ca-cert
  labels:
    {{- include "dify.labels" . | nindent 4 }}
data:
  ca.pem: |-
    {{ .Values.customCACert | default "" | nindent 4 }} 